name: Build, Test and License

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test RaceConditions Extended
      run: go test -bench=. -benchtime=10s  -test.parallel 1 -race -v

    - name: Setup License Server
      run: go install github.com/google/go-licenses@latest

    - name: Check Licenses
      run: go-licenses check "github.com/asap2Go/calibrationReader" 
