name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -v
    
    - name: TestRace
      run: go test -bench=. -benchtime=10s  -test.parallel 1 -race -v

    - name: CreateLicenses
      run: go-licenses save "github.com/asap2Go/calibrationReader" --save_path "./licenses" --force

    - name: CheckLicenses
      run: go-licenses check "github.com/asap2Go/calibrationReader" 
